version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container-name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ['CMD', 'bash', '-c', "echo 'ruok' | nc localhost2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      network:
        - confluent

  broker:
    image: confluentinc/cp-server:7.4.0
networks:
  confluent: